### ISSUE TITLE
PN7150 userspace driver not working on i.MX6

### ISSUE THREAD

**Issue by h3xman** [NXPNFCLinux/linux_libnfc-nci#57]
Library is compiled with the following options:
```
 ./configure --enable-pn7150 --enable-alt --prefix=/home/test/sshfs --sysconfdir=/home/test/sshfs/etc --host=arm-linux-gnueabihf
```

Demo app does not work, although probing I2C and IRQ/EN pins shows ongoing communication.
```
#########################################################################################
##                                       NFC demo                                      ##
#########################################################################################
##                                 Poll mode activated                                 ##
#########################################################################################
                              ... press enter to quit ...

NxpTml:     System already has pin /sys/class/gpio/gpio26

NxpTml:     System already has pin /sys/class/gpio/gpio27

NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpHal:     i2c_fragmentation_status existing
NxpFwDnld:  NULL handler : unable to load the library file, specify correct path
NxpFwDnld:  Image extraction Failed - invalid imginfo or imginfolen!!
NxpFwDnld:  Error loading libpn54x_fw !!

NxpFwDnld:  Freeing Mem for Dnld Context..
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpHal:     Sending DH and NFCC core connection command as raw packet!!
NxpHal:     Sending DH and NFCC mode set as raw packet!!
NxpHal:     Sending UICC Select Command as raw packet!!
NxpHal:     Sending Set Screen ON State Command as raw packet!!
NxpHal:     Sending discovery as raw packet!!
NxpHal:     Sending last command for Recovery
NxpHal:     Invoking data callback!!
```

On the other hand, running NfcFactoryTestApp shows that packets are transmitted and received correctly:
```
----------------------------
NFC Factory Test Application
----------------------------

>> 20 00 01 01 
<< 40 00 03 00 11 01 

>> 20 01 00 
<< 40 01 19 00 03 1e 03 00 08 00 01 02 03 80 81 82 83 02 d0 02 ff 02 00 04 88 10 01 a0 
PN7150 NFC controller detected

>> 2f 00 01 00 
<< 4f 00 01 00 
Select the test to run:
         1. Continuous RF ON
         2. PRBS
         3. Standby mode
Your choice:
```

**Comment by jgeslin** [comment]
Hi,

I assume you have exact same definition in both "linux_libnfc-nci/src/halimpl/pn54x/tml/i2c/phTmlNfc_alt.h" and " linux_NfcFactoryTestApp/tml_alt.c". Am I rght ?

Regards,
Jeremy.

**Comment by h3xman** [comment]
Yes, i2c is configured identically in both cases

**Comment by jgeslin** [comment]
Any chance to spy the I2C communication and to see the difference ?
Basically both the NfcFactoryTestApp and the linux_libnfc-nci implement access to PN7150 in the same way, so there should be no difference in behavior.

Regards,
Jeremy.

**Comment by h3xman** [comment]
I've probed I2C lines while running both NfcFactoryTestApp and linux_libnfc. Communication looks OK to me.
![i2c](https://user-images.githubusercontent.com/33279520/32723077-31c84884-c87d-11e7-99ce-ed3fda982755.png)

Sometimes I get "Waiting for NFC tag" message after a few errors. Saleae Logic dumps for both apps: [nfc.zip](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1466578/nfc.zip)

**Comment by jgeslin** [comment]
Hi,

Looking to libnfc-nci.logicdata trace I see the communication running smoothly (as expected) until the start of the discovery. From this perspective all looks ok, the PN7150 should be at this stage able to detect any NFC remote device. 

What do you mean by "after a few errors" ?

Regards,
Jeremy.

**Comment by h3xman** [comment]
Thanks for having a look.

I meant i2c_write errors, here's complete log:
```
root@cl-som-imx6ul-sid:/smarthome/nfc# nfcDemoApp poll
#########################################################################################
##                                       NFC demo                                      ##
#########################################################################################
##                                 Poll mode activated                                 ##
#########################################################################################
                              ... press enter to quit ...

NxpTml:     System already has pin /sys/class/gpio/gpio26

NxpTml:     System already has pin /sys/class/gpio/gpio27

NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpHal:     i2c_fragmentation_status existing
NxpFwDnld:  NULL handler : unable to load the library file, specify correct path
NxpFwDnld:  Image extraction Failed - invalid imginfo or imginfolen!!
NxpFwDnld:  Error loading libpn54x_fw !!

NxpFwDnld:  Freeing Mem for Dnld Context..
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpHal:     Sending DH and NFCC core connection command as raw packet!!
NxpHal:     Sending DH and NFCC mode set as raw packet!!
NxpHal:     Sending UICC Select Command as raw packet!!
NxpHal:     Sending Set Screen ON State Command as raw packet!!
NxpHal:     Sending discovery as raw packet!!
NxpHal:     Sending last command for Recovery
NxpHal:     Invoking data callback!!
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpTml:     _i2c_write() errno : 5
NxpTml:     PN54X - Error in I2C Write.....

NxpHal:     write error status = 0x1ff
NxpHal:     write_unlocked failed - PN54X Maybe in Standby Mode - Retry
NxpFwDnld:  Clock frequency value is wrong in config file, setting it as default
NxpHal:     Sending DH and NFCC core connection command as raw packet!!
NxpHal:     Sending DH and NFCC mode set as raw packet!!
NxpHal:     Sending UICC Select Command as raw packet!!
NxpHal:     Sending Set Screen OFF State Command as raw packet!!
NxpHal:     Sending last command for Recovery
NxpHal:     Invoking data callback!!
Waiting for a Tag/Device...
```

No tags are detected after this message appears. Also, probing pin TX1 on PN7150 shows that antenna is only active for a brief period of time after launching the application.

I also tried a completely different platform (OrangePi, Allwinner SoC) with PN7150 demo kit to eliminate any hardware faults. Same results - I can't get linux_libnfc-nci to work, but NfcFactoryTestApp works.

**Comment by jgeslin** [comment]
Hi,

Those errors relates to the initial request (where PN7150 is sleeping) then to a FW update mode (not supported by PN7150). All seems to run as expected then.
When "Waiting for a Tag/Device..." is displayed it means PN7150 discovery loop is started. In this mode the PN7150 is regularly (every half second) generating RF field for a small period of time to discover remote NFC device. If this is stopped, please check stability of VANT supply.

Regards,
Jeremy.

**Comment by jgeslin** [comment]
Which tag are you using ?

**Comment by h3xman** [comment]
Yes, I'm using the NFC sample cards that came with the kit

**Comment by jgeslin** [comment]
Please enable NCI traces (NXPLOG_NCIX_LOGLEVEL and NXPLOG_NCIR_LOGLEVEL set to 0x03 in /etc/libnfc-nxp.conf) and provides logs from the start of the application until unsuccessful tap of the card.

**Comment by h3xman** [comment]
Tried tapping different cards a few times but nothing new in the [log](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1470410/log.txt)

**Comment by jgeslin** [comment]
Indeed something looks strange in the log.
Please update more trace by updating src\halimpl\pn54x\log\phNxpLog.h file to set ENABLE_API_TRACES to TRUE and rebuild the library. Then provide new log of the issue.

**Comment by h3xman** [comment]
Done: [log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1474427/log.txt).

**Comment by jgeslin** [comment]
We are still missing some traces in the log. My mistake, I forgot to indicate you to set APPL_TRACE_LEVEL and PROTOCOL_TRACE_LEVEL to 0xFF inside /etc/libnfc-brcm.conf file.
Please provide new log with this setting for analysis.

**Comment by h3xman** [comment]
Done, thanks for having a look. [log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1477676/log.txt)

**Comment by jgeslin** [comment]
From the last log, it seems you are facing timeout on a NCI command response leading to recovery while the response is coming hereafter:
```
NxpNciX:     len =   4 > 21060100
NxpTml:     PN54X - I2C Write successful.....
NxpTml:     PN54X - Posting Fresh Write message.....
NxpTml:     PN54X - Tml Writer Thread Running................
NxpHal:     write successful status = 0x0
NxpFunc:    Brcm: nfa_dm_disc_sm_execute(): new state: 1,  disc_flags: 0x22
NxpFunc:    Brcm: nfa_sys_ptim_stop_timer 76ecdab0
NxpFunc:    Brcm: ptim timer stop
NxpFunc:    Brcm: Stopped presence check timer (if started)
NxpFunc:    Brcm: nfc_ncif_cmd_timeout
NxpFunc:    Brcm: Recovery Start!
NxpFunc:    Brcm: Last State nfa_dm_cb.disc_cb.disc_flags 0x22
NxpFunc:    Brcm: Last State nfa_dm_cb.disc_cb.disc_state 0x1
NxpFunc:    Brcm: Last State is Discovery!!
NxpFunc:    Brcm: connection id 3
NxpFunc:    NfcAdaptation::HalCoreInitialized
NxpTml:     PN54X - I2C Read successful.....
NxpNciR:     len =   4 > 41060100
```

Can you try increasing the NFC_CMD_CMPL_TIMEOUT parameter (in src\libnfc-nci\include\nfc_target.h file) ?

**Comment by h3xman** [comment]
I've set NFC_CMD_CMPL_TIMEOUT to 10 and I'm no longer getting a timeout, but still no tags are detected. 
[log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1482250/log.txt)

**Comment by jgeslin** [comment]
There is still timeout issue, later in the log:
```
NxpNciX:     len =  28 > 2103190C000101010201030105018001810182018301850106017001
NxpTml:     PN54X - I2C Write successful.....
NxpTml:     PN54X - Posting Fresh Write message.....
NxpTml:     PN54X - Tml Writer Thread Running................
NxpHal:     write successful status = 0x0
NxpFunc:    Brcm: nfc_ncif_cmd_timeout
NxpFunc:    Brcm: Recovery Start!
```
This occurs at the last stage of the initialization, when starting the discovery. Try to increase again the timeout.

**Comment by h3xman** [comment]
Changed the value to 30 - no luck: [log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1482485/log.txt)

**Comment by jgeslin** [comment]
Still timeout occur:
```
NxpNciX:     len =  28 > 2103190C000101010201030105018001810182018301850106017001
NxpTml:     PN54X - I2C Write successful.....
NxpTml:     PN54X - Posting Fresh Write message.....
NxpTml:     PN54X - Tml Writer Thread Running................
NxpHal:     write successful status = 0x0
NxpFunc:    Brcm: nfc_ncif_cmd_timeout
```

Looks to me that there is something wrong with the timer handling (NFC_CMD_CMPL_TIMEOUT being defined in seconds).

Please use attached file which add timestamp to the logs: 
[phNxpLog.zip](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1482989/phNxpLog.zip)

**Comment by h3xman** [comment]
OK, I've recompiled the library with timestamp and tried setting NFC_CMD_CMPL_TIMEOUT to 60 seconds: [log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1486692/log.txt)

**Comment by jgeslin** [comment]
Indeed we are missing the answer to the "2103..." NCI start discovery command while it should come !
Do you have the ability to check the PN7150 IRQ line status at this time ? It should be high, indicating the answer is ready to be fetched by the host via I2C.

**Comment by h3xman** [comment]
IRQ line is pulled high briefly after 1ms from the "210319.." request.

![i2c_irq](https://user-images.githubusercontent.com/33279520/33015559-428fe472-cdfc-11e7-8ba7-4d14e7c743f3.png)

Communication looks fine to me, although I could have messed things up a bit after soldering wires for the logic analyzer, since I'm getting some 'i2c_read()' errors in the log that weren't present before. I'll have to check signal integrity with a scope as well.

[log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1487355/log.txt)

[libnfc-nci-irq.logicdata.zip](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1487353/libnfc-nci-irq.logicdata.zip)

**Comment by jgeslin** [comment]
Nothing can explain the IRQ line going low, just after a few µs, except a HW reset (no VBAT or VEN pin low).
The logic analyser log seems anyway strange, the "short pulse" of IRQ is indicating lasting ~60s !
Can you confirm (using scope or voltage meter) that the IRQ is indeed going low during the 60 ms timeout ?

**Comment by h3xman** [comment]
Indeed, that is strange, for some reason I though that IRQ is active high. I'll have to check if any pull-ups are enabled in the device tree

**Comment by jgeslin** [comment]
I confirm IRQ is active high. If you look to previous exchanges in the log, you can see that when the IRQ is going high, the host perform Read request, then when the read is completed (complete NCI frame is read) the IRQ goes low (driven by PN7150). There should not be any pull-up/down resistor on this line.

**Comment by h3xman** [comment]
I checked device tree - IRQ pin is not referenced anywhere. I've set this pin to 0x80000000 to enforce default values. There are no external pull-up/down resistors on the PCB. I've been monitoring IRQ line with a scope and haven't seen anything strange, except for one anomaly:

![irq](https://user-images.githubusercontent.com/33279520/33064149-cfe909de-ceb5-11e7-90eb-baf5953f9aab.png)

I've seen this happening twice: at the very beginning of the communication when I start the nfcDemoApp and right after the 60s delay. Pulse duration is 100ms

**Comment by jgeslin** [comment]
Not sure to understand what mean this scope diagram.
Anyway, where you able to confirm this really short pulse on IRQ line after the "2103190C000101010201030105018001810182018301850106017001" leading to the 60s timeout ?

**Comment by h3xman** [comment]
Sorry, I was referring to a slight step at the beginning of the waveform, which seemed odd, although it's above logic threshold level and shouldn't cause problems.

The short spike was most likely caused by the logic analyzer and long wires:
![irq_la](https://user-images.githubusercontent.com/33279520/33068071-32e6fa5e-cec1-11e7-92ff-2cf0a0c107f5.png)

When LA is disconnected I can see that IRQ stays low after the 2103.. request.

**Comment by jgeslin** [comment]
Can you retry after updating libnfc-brcm.conf file with "P2P_LISTEN_TECH_MASK=0x05" and provide new log ?

**Comment by h3xman** [comment]
Done
[log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1491451/log.txt)

**Comment by jgeslin** [comment]
Can you retry with "P2P_LISTEN_TECH_MASK=0x01" and provide new log ?

**Comment by h3xman** [comment]
[log.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci/files/1491541/log.txt)

**Comment by jgeslin** [comment]
I'm suspecting a drop on the power supply. Can you monitor VBAT and PVDD during this last stage of the communication ?

**Comment by h3xman** [comment]
I assume by PVDD you mean pin 6 - VDD(PAD)? Supply voltage is solid, no issues here. There is a voltage drop on VBAT pins, which happens right after the 60s timeout:

![vbat](https://user-images.githubusercontent.com/33279520/33114943-2788d6be-cf70-11e7-9660-c7c3e905dd29.png)

I'll try adding more decoupling capacitors and check again.

**Comment by h3xman** [comment]
Indeed, the issue was related to insufficient decoupling on VBAT pins. Thanks for helping me out!
